name: Deploy to Azure

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-and-deploy-api:
    name: Build & Deploy Backend API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore api/RentLanka.Api.csproj

      - name: Publish API
        run: dotnet publish api/RentLanka.Api.csproj -c Release -o ./publish-api --no-restore

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: rentlanka-api
          package: ./publish-api
